config/routes.rb
Rails.application.routes.draw do

  get '/search' => 'pages#search', :as => 'search_page'
  get 'session/new'
  root to: "pages#home"

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  resources :users
  resources :loans
  resources :games
  resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :games
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user, optional: true ### owner
  has_many :loans ## ordernumber
  has_and_belongs_to_many :categories

  def available?
    #1.does the game have any loans at all if not then it must be available
    return true unless loans.any?
    loans.where("TIMESTAMP 'now' >= start_date AND TIMESTAMP 'now' < end_date").empty?
  end

end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :game, optional: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  has_many :loans
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :fetch_user

  def fetch_user
    if session[:user_id].present?
    @current_user = User.find_by id: session[:user_id]
    end
    session[:user_id] = nil unless @current_user.present?
  end

  def check_if_logged_in
    unless @current_user.present?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

    def check_for_admin
      redirect_to root_path unless @current_user.present? && @current_user.admin?
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :check_for_admin, :only => [:edit, :update, :destroy]

  def new
    @category = Category.new
  end

  def create
    @category = Category.create category_params
    redirect_to login_path unless session[:user_id] == @current_user.id ###only users can add new categories
    redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find params[:id]
    @game = Game.where(category_id: params[:id])
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    category = Category.find params[:id]
    category.update category_params
    redirect_to categories_path
  end

  def destroy
    Category.destroy params[:id]
    redirect_to categories_path
  end

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :check_for_admin, :only => [:edit, :update, :destroy]

  def new
    @game = Game.new
  end

  def create
    @game = Game.create game_params

    @game.categories << Category.find(params[:game][:category_id])
    if params[:game][:box_art].present?
      response = Cloudinary::Uploader.upload params[:game][:box_art]
      p response
      #save response Id into the appropriate field of our new model
      @game.box_art = response["public_id"]

    end
    @game.user_id = @current_user.id
    @game.save
    redirect_to games_path

  end

  def index
    @games = Game.all
  end

  def show
    @game = Game.find params[:id]
    @loan = @game.loans.find_by("TIMESTAMP 'now' >= start_date AND TIMESTAMP 'now' <= end_date")
    @categories = Category.where(game_id: params[:id])
  end

  def edit
    @game = Game.find params[:id]
    flash[:error] = "Only The Owner of that game can edit it" unless @game.user_id == @current_user.id || @current_user.admin?
  end

  def update
    @game= Game.find params[:id]
    flash[:error] = "Only The Owner of that game can edit it" and return unless @game.user_id == @current_user.id || @current_user.admin?
    @game.categories.delete_all
    if params[:game][:category_id].any?
      @game.categories << Category.find(params[:game][:category_id])
    end
    @game.update game_params
    redirect_to game_path(@game.id)
  end

  def destroy
    Game.destroy params[:id]
    flash[:error] = "Only The Owner of that game can edit it" unless @game.user_id == @current_user.id || @current_user.admin?
    redirect_to games_path
  end

  private
  def game_params
    params.require(:game).permit(:title, :description, :min_players, :max_players, :available, :contents, :missing_damage, :user_id, :category_id, :box_art)
  end


end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def new
    @loan = Loan.new
    @loans = Loan.all
  end

  def create
    loan = Loan.create loan_params
    loan.user_id = @current_user.id
    if loan.game.available? == false
      redirect_to new_loan_path
      flash[:error] = "That Game is unavailable at this time"
    else
      loan.save
      redirect_to loans_path
    end
  end

  def index
    @loans = Loan.all
  end

  def show
    @loan = Loan.find params[:id]
  end

  def edit
    @loan = Loan.find params[:id]
    redirect_to login_path unless @loan.user_id == @current_user.id
  end

  def update
    @loan = Loan.find params[:id]
    redirect_to login_path unless @loan.user_id == @current_user.id
    @loan.update loan_params
    redirect_to loan_path(@loan.id)
  end

  def destroy

    if @loan.user.id == @current_user.id
      @loan = Loan.destroy params[:id]
    redirect_to loans_path
    else
      flash[:error] = "You must be the user to delete a loan"
    redirect_to login_path
    end

  end

  private
  def loan_params
    params.require(:loan).permit(:user_id, :game_id, :start_date, :end_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  # def search
  #   if params[:search].blank?
  #
  #   else
  #     @parameter = params[:search].downcase
  #     @results = Category.all.where("lower(name) LIKE :search", search: "%#{@parameter}%").order("categories.name DESC")
  #
  #   end
  # end    -code for a search function currently only searches one class and errors if you navigate off the page without searching

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user= User.find_by contact: params[:contact]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end

    def destroy
      session[:user_id]=nil
      redirect_to login_path
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.persisted?
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end

  end

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
    @loans = Loan.where(user_id: params[:id])
  end

  def edit
    @user = User.find params[:id]
    :check_for_admin
  end

  def update
    user = User.find params[:id]
    :check_for_admin
    user.update user_params
    redirect_to user_path(user.id)
  end

  def destroy
    User.destroy params[:id]
    :check_for_admin
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :contact, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/borrowers/edit.html.erb
<h1>Borrower something</h1>

<%= render partial: 'form' %>

app/views/categories/_form.html.erb
<%= form_with model:@category, local:true do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<%end %>

app/views/categories/edit.html.erb
<h1>Edit Categories: <%= @category.name %></h1>
<%= render partial: 'form' %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<ul class='categories'>
  <% @categories.each do |c| %>
  <li>
    <%= link_to c.name, category_path(c.id)%>
  </li>
  <% end %>

</ul>

<% if @current_user.present? %>
<%= link_to "Add a Category ", new_category_path %>
<% else %>

<% end %>

app/views/categories/new.html.erb
<h1>Add a Categories</h1>

<%= render partial: 'form' %>

app/views/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>

<ul>
  <% @category.games.pluck(:title).each do |n| %>
    <li><%= link_to n, game_path(@category.games.ids) %></li>

  <% end %>


</ul>



<br>
<% if :check_for_admin == true%>
<%= link_to "Edit this Category", edit_category_path(@category.id) %>
<%= link_to "Delete this Category", category_path(@category.id), method: 'delete' %>
<% end %>

app/views/games/_form.html.erb
<%= form_with model:@game, local:true, class: 'add-game', html: {multipart: true} do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<%= f.label :user_id %>
<%= f.collection_select :user_id, User.all, :id, :name, include_blank: true %>
<br>
<%= f.label :min_players %>
<%= f.text_field :min_players %>
<br>
<%= f.label :max_players %>
<%= f.text_field :max_players%>
<br>
<%= f.label :description %>
<%= f.text_field :description %>
<br>
<%= f.label :category_id%>
<table class='category-table'>
  <%= f.collection_check_boxes :category_id, Category.all, :id, :name, include_hidden: false do |box| %>

   <th><%=box.label {box.check_box(checked: @game.categories.include?(box.object)) + box.text}  %></th>
  <% end %>
</table>
<br>


<br>
<%= f.label :contents %>
<%= f.text_field :contents %>
<br>
<%= f.label :missing_damage %>
<%= f.text_field :missing_damage %>
<br>
<%= f.label :box_art %>
<%= f.text_field :box_art %>
<%= f.file_field :box_art %>
<br>
<%= f.submit %>
<% end %>

app/views/games/edit.html.erb
<h1>Edit <%= @game.title %></h1>


<%= render partial: 'form' %>

app/views/games/index.html.erb
<h1>Games</h1>
<table>
  <tr>
    <th>Game</th>
    <th>Availibilty</th>
  </tr>


      <% @games.each do |g| %>
  <tr>
    <td> <%= link_to g.title, game_path(g.id) %></td>

    <td><%= g.available? ? 'Available' : 'Not Available'%></td>

      <% end %>

</table>
<br>

<%= link_to "Add a Game", new_game_path %>

app/views/games/new.html.erb
<h1>Add a Game</h1>
<%= render partial: 'form' %>

app/views/games/show.html.erb
<h1> <%= @game.title %></h1>

<div class='games-background'  style='background-image: url(<%= Cloudinary::Utils.cloudinary_url(@game.box_art, width: 50, height: 100, crop: :fill) %>)'>

  <div class='games'>
    <ul class='games'>


      <li>Player(s):
        <%= @game.min_players%> - <%=@game.max_players %>
      </li>
      <br>

      <li>Available:
        <% if @game.available? %>
         Yes
        <% else %>
        Not Available
        <br>
        Currently Borrowed by:
        <%= @loan.user.name %>
        <% end %>
      </li>
      <br>

      <li>Description:
        <%= @game.description %>
      </li>
      <br>
      <li>Categories:
        <% @game.categories.pluck(:name).each do |n| %>
          <li><%= n %></li>

        <% end %>
      </li>
      <br>
      <li>Contents:
        <%= @game.contents %>
      </li>
      <br>
      <li>Is anything missing or damaged?:
        <%= @game.missing_damage %>
      </li>
      <br>


    </ul>
  </div>
</div>
<%= link_to "Edit Game", edit_game_path(@game.id) %> ||
<% if :check_for_admin == true%>
<%= link_to "Delete Game", game_path(@game.id), method:'delete' %> ||
<% end %>



<%= form_with model: Loan.new, local: true do |f| %>
<% if session[:user_id].present?%>
<%= @current_user.name %>
<%else %>
<%= link_to "Login in to Borrow this game", login_path %>
<%end %>
<br>



<%= f.hidden_field :game_id, value: @game.id, class: 'date_field'%>
<br>
<%= f.label :start_date %>
<%= f.date_field :start_date, class: 'date_field'%>
<br>
<%= f.label :end_date %>
<%= f.date_field :end_date, class: 'date_field'%>
<br>

<%= f.submit class: 'button' %>
<% end %>

app/views/layouts/_form.html.erb
<% form_with %>

<%= f.label %>
<%= f.search_field :games, :title, autosave: false%>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id='title'>
    <h1>Game Library</h1>
    <% if @current_user.present? %>
      Welcome,<%=link_to @current_user.name, user_path(@current_user.id), class:'name' %>
      <%end %>
    </div>
    <nav>

      <% if @current_user.present? %>

        <div class='log'>
        <%= link_to 'Logout', login_path, method:'delete', class: 'log' %>
        </div>
        <div class='log'>
        <%= link_to "Users", users_path, class:'log'%>
        </div>


        <% else %>
        <div class='log'>
        <%= link_to 'Login', login_path, class: 'log' %>
        </div>
        <div class='log'>
        <%= link_to 'Sign Up', new_user_path, class: 'log' %>
      <% end %>
        </div>

      <div class='loans'>
      <%= link_to "All Currently Borrowed items", loans_path%>
      </div>
      <div class='lib' >
      <%= link_to "Games", games_path, class: 'lib'%>
      </div>
      <div class='lib'>
      <%= link_to "Categories", categories_path, class: 'lib'%>
      </div>

    </nav>
    <div class='page'>
    <%= yield %>
    </div>
  </body>
</html>

app/views/loans/_form.html.erb
<%= form_with model:@loan, local: true do |f| %>


<br>
<%= f.label :game_id %>
<%= f.collection_select :game_id, Game.all, :id, :title, include_blank: true, class: 'drop_down'%>
<br>
<%= f.label :start_date %>
<%= f.date_field :start_date, class: 'date_field'%>
<br>
<%= f.label :end_date %>
<%= f.date_field :end_date, class: 'date_field'%>
<br>

<%= f.submit class: 'button' %>
<% end %>

app/views/loans/edit.html.erb
<h1>Edit Your Loan</h1>
<%= render partial: 'form' %>

app/views/loans/index.html.erb
<h1>Loans</h1>



<div>
  <p>
    Currently Borrowed
  </p>
<table>
  <tr>
    <th>Game Title</th>
    <th>Borrowed By</th>
    <th>Return Date</th>
  </tr>
      <% @loans.each do |l| %>
      <% if Date.today >= l.start_date  and Date.today <= l.end_date%>
  <tr>
    <td> <%= link_to l.game.title, game_path(l.game.id) %></td>
    <td><%= link_to l.user.name, user_path(l.user) %></td>
    <td><%=  link_to l.end_date, loan_path(l.id)%></td>

  </tr>
      <% end %>
      <% end %>
  </table>
  </div>

  <div>
    <p>
      Previously Borrowed
    </p>
<table>
    <tr>
      <th>Game Title</th>
      <th>Borrowed By</th>
    </tr>
      <% @loans.each do |l| %>
      <% if Date.today > l.end_date %>
    <tr>
      <td><%= link_to l.game.title, game_path(l.game.id) %></td>
      <td><%= link_to l.user.name, user_path(l.user) %></td>
    </tr>
      <% end %>
      <% end %>

</table>
</div>

<br>
<div>
  <p>
    Next to Be Borrowed
  </p>
<table>
  <tr>
    <th>Game Title</th>
    <th>Borrowed By</th>
    <th>Will be Borrowed on</th>
  </tr>
      <% @loans.each do |l| %>
      <% if Date.today < l.start_date %>
  <tr>
    <td><%= link_to l.game.title, game_path(l.game.id) %></td>
    <td><%= link_to l.user.name, user_path(l.user) %></td>
    <td><%=  link_to l.start_date, loan_path(l.id)%></td>
  </tr>
      <% end %>
      <% end %>

</table>
</div>

<br>

<%= link_to "Borrow Some Games", new_loan_path %>

app/views/loans/new.html.erb
<h1><%= @current_user.name %>-Loan something out!</h1>

<% if flash[:error] %>
<br>
<strong><%= flash[:error] %></strong><br>
<div>
  <p>
    Currently Borrowed
  </p>
<table>
  <tr>
    <th>Game Title</th>
    <th>Borrowed By</th>
    <th>Return Date</th>

  </tr>
      <% @loans.each do |l| %>
      <% if Date.today >= l.start_date %>
  <tr>
    <td><%= link_to l.game.title, game_path(l.game.id) %></td>
    <td><%= link_to l.user.name, user_path(l.user) %></td>
    <td><%=  link_to l.end_date, loan_path(l.id)%></td>

  </tr>
      <% end %>
      <% end %>
  </table>
<%= link_to "Borrow Another Game", new_loan_path %>
<% else %>
<%=render partial: 'form' %>
<% end %>
<br>

app/views/loans/show.html.erb
<h1>Loan #<%= @loan.id %></h1>


<label>User:</label>
<%= @loan.user.name %>
<br>
<label>Game:</label>
<%= @loan.game.title  %>
<br><label>Start Date:</label>
<%=@loan.start_date %>
<br><label>End Date:</label>
<%= @loan.end_date %>
<br>
<% if @current_user == @loan.user || @current_user.admin? %>
  <%= link_to "Edit This Loan", edit_loan_path(@loan.id) %>
  
  <% end %>
  <% if @current_user.admin? %>
        <%= link_to "Delete This Loan", loan_path(@loan.id), method: 'delete' %>
    <% end %>

app/views/pages/home.html.erb
<h1>Welcome to the Games Library</h1>

<div>
<%= link_to "Look at our list of Games", games_path  %>
</div>

<div>
  <%= link_to "Find Games by Category", categories_path  %>
</div>

app/views/pages/search.html.erb
<h3>Search Result</h3>

<% @results.each do |r| %>
<%= r.name %>
<% end %>

app/views/session/new.html.erb
<h1>Login</h1>

<div class='login'>
  <% if flash[:error] %>
  <br>
  <strong><%= flash[:error] %></strong>
  <% end %>
  <br>
  <br>

  <%= form_with url: login_path, local:true do |f| %>
  <%= f.label :contact, "Email" %>
  <%= f.text_field :contact, id: 'login_email'%>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password, id: 'login_password' %>
  <br>
  <%= f.submit "Login", id: 'login_button'%>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |f|%>


<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :contact %>
<%= f.text_field :contact %>
<br>
<%= f.label :password %>
<%= f.password_field :password %>
<br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<br>
<%= f.submit "Sign Up" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user: <%= @user.id %></h1>
<%= render partial: 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>
<% if :check_for_admin  %>
    <ul>
    <% @users.each do |u| %>
    <li>
      <%= link_to u.name, user_path(u.id) %>
    </li>
    <% end %>
    </ul>

      <%= link_to "Add new User", new_user_path %>

<% else %>
      <ul>
      <% @users.each do |u| %>
      <li>
        <%= u.name %>
      </li>
      <% end %>
      </ul>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up </h1>

<% if @user.errors.full_messages.any? %>
<strong>Please Correct the following errors:</strong>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
    <li> <%= error %></li>
    <% end %>
  </ul>

<% end %>

<%= render partial: 'form' %>

app/views/users/show.html.erb
<h1>Welcome -<%= @user.name %></h1>

<div id='user_info'>
  <ul>

    <br>

    <li>Contact:
      <%= @user.contact %>
    </li>
    <br>

    <li>Admin:
      <% if @user.admin? %>
      <%= "Yes" %>
      <% else %>
      <%= "No" %>
      <%end %>
    </li>
    <br>
      <%= link_to "Edit User", edit_user_path(@user.id) %>
      <%= link_to "Delete User", user_path(@user.id), method: 'delete' %>
    <br>
  </ul>
</div>

<p>
  Currently Borrowed
    <table>
      <tr>
        <th>Game Title</th>
        <th>Borrowed On</th>
      </tr>
      <% @loans.each do |l| %>
      <% if Date.today >= l.start_date %>
      <tr>
        <td><%= link_to l.game.title, game_path(l.game.id) %></td>
        <td><%= link_to l.start_date, user_path(l.user) %></td>
      </tr>
      <% end %>
      <% end %>
    </table>
</p>

<p>
  Next to be Borrowed
    <table>
      <tr>
        <th>Game Title</th>
        <th>Borrowed On</th>
      </tr>
      <% @loans.each do |l| %>
      <% if Date.today <= l.start_date %>
      <tr>
        <td><%= link_to l.game.title, game_path(l.game.id) %></td>
        <td><%= link_to l.start_date, user_path(l.user) %></td>
      </tr>
      <% end %>
      <% end %>
    </table>
</p>

<p>
  Previously Borrowed
    <table>
      <tr>
        <th>Game Title</th>
        <th>Borrowed on</th>
        <th>Returned on</th>
      </tr>
      <% @loans.each do |l| %>
      <% if Date.today >= l.end_date %>
      <tr>
        <td><%= link_to l.game.title, game_path(l.game.id) %></td>
        <td><%= link_to l.start_date, user_path(l.user) %></td>
        <td><%= link_to l.end_date, user_path(l.user) %></td>
      </tr>
      <% end %>
      <% end %>
    </table>
</p>

<div>
  <%= link_to "Edit Your User Profile", edit_user_path(@current_user.id)%>
</div>

<div>
  <%= link_to "Add New Games to the Library", new_game_path %>
</div>